name: star23sharp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  provider: ^6.1.2
  googleapis_auth: ^1.6.0
  flutter_local_notifications: ^17.2.4
  geolocator: ^13.0.1
  kakao_map_plugin: ^0.3.2
  flutter_gif: ^0.0.4
  flutter_dotenv: ^5.2.1
  webview_flutter: ^4.9.0
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  firebase_analytics: ^11.3.3
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  overlay_support: ^2.1.0
  logger: ^2.4.0
  flutter_secure_storage: ^9.2.2
  dart_openai: ^5.1.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.5
  intl: ^0.19.0
  flutter_image_compress: ^2.3.0
  path: ^1.9.0
  http_parser: ^4.0.2
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/img/
    - assets/img/blackTheme/
    - assets/img/logo/
    - assets/img/map/
    - assets/img/planet/
    - assets/icon/
    - assets/data/

  fonts:
    - family: Hakgyoansim Chilpanjiugae
      fonts:
        - asset: assets/fonts/Hakgyoansim_Chilpanjiugae_OTF_B.otf
        - asset: assets/fonts/Hakgyoansim_Chilpanjiugae_OTF_L.otf
        - asset: assets/fonts/Hakgyoansim_Chilpanjiugae_TTF_B.ttf
        - asset: assets/fonts/Hakgyoansim_Chilpanjiugae_TTF_L.ttf
